project:
  type: book
  # resources: 
  #   - "archive"
  output-dir: _site
  render:
    - index.md
    - setup.md
    - versions.md
    - materials/*
    - "!materials/*/no_render"
    - "!archive"

format: crit-format-html

filters: 
  - callout-exercise

execute:
  freeze: auto

knitr:
  opts_knit:
    cache.path: .knitr_cache

metadata-files:
  - "materials/_chapters.yml"
  # - "materials/_sidebar.yml"

book:
  search:
    location: sidebar
  favicon: "_extensions/tavareshugo/crit-format/img/university-of-cambridge-favicon.ico"
  page-navigation: true
  page-footer: 
    center: |
      Licensed [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) 
      ![](https://creativecommons.org/images/deed/cc_icon_black_x2.png){width=25px} 
      Cambridge Research Informatics Training
  navbar:
    pinned: true
    logo: "_extensions/tavareshugo/crit-format/img/university_crest_reversed.png"
    right:
      - text: "{{< iconify fa6-brands github size=lg title='CRIT GitHub' >}}"
        href: https://github.com/cambiotraining/
      - text: "{{< iconify fa6-brands bluesky size=lg title='CRIT Bluesky' >}}"
        href: https://bsky.app/profile/bioinfocambs.bsky.social
      - text: "{{< iconify fa6-brands mastodon size=lg title='CRIT Mastodon' >}}"
        href: https://genomic.social/@BioInfoCambs
      - text: "{{< iconify mdi web size=lg title='CRIT Website' >}}"
        href: https://bioinfotraining.bio.cam.ac.uk/
    title: "Testing Versions"
  chapters:
    - part: "Welcome"
      chapters:
        - text: "Introduction"
          href: index.md
        - text: "Data & Setup"
          href: setup.md
  appendices: 
    - text: "Archived Versions"
      href: versions.md