name: Deploy Latest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Deploy
        uses: tavareshugo/test-gh-actions/deploy@main
        with:
          pre_render: "echo 'Optional pre-render commands'"
          post_render: "echo 'Optional post-render commands'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
