name: Deploy Latest

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    uses: tavareshugo/test-gh-actions/deploy/action.yml@main
    with:
      pre_render: "echo 'Optional pre-render commands'"
      post_render: "echo 'Optional post-render commands'"