name: Deploy Latest

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    needs: call-archive
    uses: tavareshugo/test-gh-actions/deploy@main
    with:
      pre_render: "echo 'Optional pre-render commands'"
      post_render: "echo 'Optional post-render commands'"