name: Deploy Latest

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["Tag Release"]
    types:
      - completed

jobs:
  call-deploy-latest:
    if: >
      github.event_name != 'workflow_run' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    uses: tavareshugo/test-gh-actions/blob/main/.github/workflows/deploy_latest.yml@main
    with:
      pre_render: "echo 'Optional pre-render commands'"
      post_render: "echo 'Optional post-render commands'"
