on:
  push:
    tags: 
      - "v*.*.*"

name: New Release

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.2.112
          
      - name: Add deprecation warning
        run: bash ./.github/scripts/release.sh

      - name: Render Site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Release
        uses: softprops/action-gh-release@v1