on:
  push:
    tags:
      - "v*.*.*"

name: Release

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TAG: 
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1