on:
  push:
    branches: 
      - release

name: Create Release

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1