name: Create Archive Version

on:
  push:
    tags:
      - '20[2-9][0-9].[0-1][0-9].[0-3][0-9]'  # Matches YYYY.MM.DD format

jobs:
  create-archive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout tagged version
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}  # This checks out the tagged commit
    
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
        
    - name: Extract tag name
      id: tag
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Creating archive for version: $TAG_NAME"
        
    - name: Render tagged version
      run: |
        quarto render
        
    - name: Prepare archive directory
      run: |
        # Rename _site to the tag name
        mv _site ${{ steps.tag.tag_name }}
        echo "Archive directory created: ${{ steps.tag.tag_name }}"
        
    - name: Checkout gh-pages branch for archive
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: _site
        
    - name: Setup archive structure
      run: |
        # Create archive directory if it doesn't exist
        mkdir -p _site/archive
        
        # Copy the new version into the archive
        cp -r ${{ steps.tag.tag_name }} _site/archive/

        # List contents for verification
        echo "Archive contents:"
        ls -la gh-pages-checkout/archive/
        
    - name: Update all versions pages and dropdowns
      run: |
        python .github/scripts/update-dropdown.py
        
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: gh-pages-checkout
        single-commit: true