name: Tag Release

on:
  push:
    tags:
      - '20[2-9][0-9].[0-1][0-9].[0-3][0-9]'

jobs:
  call-tag-release:
    uses: tavareshugo/test-gh-actions/.github/workflows/tag_release.yml@main
    with:
      pre_render: "echo 'Pre-render hook for additional setup'"
      post_render: "echo 'Post-render hook for custom commands'"
