name: Tag Release

on:
  push:
    tags:
      - '20[2-9][0-9].[0-1][0-9].[0-3][0-9]'

jobs:
  call-archive:
    uses: tavareshugo/test-gh-actions/archive@main
    with:
      pre_render: "echo 'Optional pre-render commands'"
      post_render: "echo 'Optional post-render commands'"
  
  call-deploy:
    needs: call-archive
    uses: tavareshugo/test-gh-actions/deploy@main
    with:
      pre_render: "echo 'Optional pre-render commands'"
      post_render: "echo 'Optional post-render commands'"
